// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: protofiles/ex_services.proto

package toi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetIotDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetIotDataRequest) Reset() {
	*x = GetIotDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_ex_services_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIotDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIotDataRequest) ProtoMessage() {}

func (x *GetIotDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_ex_services_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIotDataRequest.ProtoReflect.Descriptor instead.
func (*GetIotDataRequest) Descriptor() ([]byte, []int) {
	return file_protofiles_ex_services_proto_rawDescGZIP(), []int{0}
}

func (x *GetIotDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetIotDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*IotDataMessage `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetIotDataResponse) Reset() {
	*x = GetIotDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_ex_services_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIotDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIotDataResponse) ProtoMessage() {}

func (x *GetIotDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_ex_services_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIotDataResponse.ProtoReflect.Descriptor instead.
func (*GetIotDataResponse) Descriptor() ([]byte, []int) {
	return file_protofiles_ex_services_proto_rawDescGZIP(), []int{1}
}

func (x *GetIotDataResponse) GetData() []*IotDataMessage {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_protofiles_ex_services_proto protoreflect.FileDescriptor

var file_protofiles_ex_services_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x65, 0x78, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x74, 0x6f, 0x69, 0x1a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f,
	0x65, 0x78, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x27, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x49, 0x6f, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x49,
	0x6f, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74,
	0x6f, 0x69, 0x2e, 0x49, 0x6f, 0x74, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x4f, 0x0a, 0x0e, 0x49, 0x6f, 0x74, 0x50, 0x65,
	0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x49, 0x6f, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x2e, 0x74, 0x6f, 0x69, 0x2e, 0x47, 0x65,
	0x74, 0x49, 0x6f, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x74, 0x6f, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6f, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x3b, 0x74, 0x6f,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protofiles_ex_services_proto_rawDescOnce sync.Once
	file_protofiles_ex_services_proto_rawDescData = file_protofiles_ex_services_proto_rawDesc
)

func file_protofiles_ex_services_proto_rawDescGZIP() []byte {
	file_protofiles_ex_services_proto_rawDescOnce.Do(func() {
		file_protofiles_ex_services_proto_rawDescData = protoimpl.X.CompressGZIP(file_protofiles_ex_services_proto_rawDescData)
	})
	return file_protofiles_ex_services_proto_rawDescData
}

var file_protofiles_ex_services_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protofiles_ex_services_proto_goTypes = []interface{}{
	(*GetIotDataRequest)(nil),  // 0: toi.GetIotDataRequest
	(*GetIotDataResponse)(nil), // 1: toi.GetIotDataResponse
	(*IotDataMessage)(nil),     // 2: toi.IotDataMessage
}
var file_protofiles_ex_services_proto_depIdxs = []int32{
	2, // 0: toi.GetIotDataResponse.data:type_name -> toi.IotDataMessage
	0, // 1: toi.IotPersistence.GetIotData:input_type -> toi.GetIotDataRequest
	1, // 2: toi.IotPersistence.GetIotData:output_type -> toi.GetIotDataResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protofiles_ex_services_proto_init() }
func file_protofiles_ex_services_proto_init() {
	if File_protofiles_ex_services_proto != nil {
		return
	}
	file_protofiles_ex_models_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protofiles_ex_services_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIotDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_ex_services_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIotDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protofiles_ex_services_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protofiles_ex_services_proto_goTypes,
		DependencyIndexes: file_protofiles_ex_services_proto_depIdxs,
		MessageInfos:      file_protofiles_ex_services_proto_msgTypes,
	}.Build()
	File_protofiles_ex_services_proto = out.File
	file_protofiles_ex_services_proto_rawDesc = nil
	file_protofiles_ex_services_proto_goTypes = nil
	file_protofiles_ex_services_proto_depIdxs = nil
}
